homePage: home
redirects:
  some-old-page:
    newPage: some-new-page
    code: 301
  en:
    newPage: en/home
router:
tableOfContents:
  - page: en/introduction
    icon: fas fa-home
    children:
      - page: en/introduction/what-is-hubleto
      - page: en/introduction/who-is-hubleto-for
      - page: en/introduction/how-to-use-this-guide
  - page: en/getting-started
    icon: fas fa-play
    children:
      - page: en/getting-started/registration-and-login
      - page: en/getting-started/homepage-overview
      - page: en/getting-started/menu-navigation
  - page: en/user-guide
    icon: fas fa-book
    children:
      - page: en/user-guide/crm
        children:
          - page: en/user-guide/crm/customers
          - page: en/user-guide/crm/contacts
          - page: en/user-guide/crm/calendar
          - page: en/user-guide/crm/documents
          - page: en/user-guide/crm/workflow
          - page: en/user-guide/crm/mail
          - page: en/user-guide/crm/dashboards
      - page: en/user-guide/marketing
        children:
          - page: en/user-guide/marketing/campaigns
          - page: en/user-guide/marketing/leads
      - page: en/user-guide/sales
        children:
          - page: en/user-guide/sales/suppliers
          - page: en/user-guide/sales/deals
          - page: en/user-guide/sales/products
          - page: en/user-guide/sales/orders
      - page: en/user-guide/projects
        children:
          - page: en/user-guide/projects/tasks
          - page: en/user-guide/projects/worksheets
          - page: en/user-guide/projects/projects
          - page: en/user-guide/projects/issues
      - page: en/user-guide/supply-chain
        children:
          - page: en/user-guide/supply-chain/warehouses
          - page: en/user-guide/supply-chain/inventory
      - page: en/user-guide/finance
        children:
          - page: en/user-guide/finance/invoices
      - page: en/user-guide/maintenance
        children:
          - page: en/user-guide/maintenance/notifications
          - page: en/user-guide/maintenance/settings
          - page: en/user-guide/maintenance/tools
