homePage: home
redirects:
  some-old-page:
    newPage: some-new-page
    code: 301
  en:
    newPage: en/home
router:
tableOfContents:
  - page: en/introduction
    icon: fas fa-home
    children:
      - page: en/introduction/what-is-hubleto
      - page: en/introduction/who-is-hubleto-for
      - page: en/introduction/how-to-use-this-guide
  - page: en/getting-started
    icon: fas fa-play
    children:
      - page: en/getting-started/registration-and-login
      - page: en/getting-started/homepage-overview
      - page: en/getting-started/menu-navigation
  - page: en/user-guide
    icon: fas fa-book
    children:
      - page: en/user-guide/crm
      - page: en/user-guide/marketing
      - page: en/user-guide/sales
      - page: en/user-guide/projects
      - page: en/user-guide/supply-chain
      - page: en/user-guide/finance
      - page: en/user-guide/maintenance
