homePage: home
redirects:
  some-old-page:
    newPage: some-new-page
    code: 301
router:
tableOfContents:
  - page: en/introduction
    icon: fas fa-home
    children:
      - page: en/what-is-hubleto
      - page: en/who-is-hubleto-for
      - page: en/how-to-use-this-guide
  - page: en/getting-started
    icon: fas fa-home
    children:
      - page: en/registration-and-login
      - page: en/homepage-overview
      - page: en/menu-navigation
  - page: en/crm
    icon: fas fa-user-tie
    children:
      - page: en/customers
      - page: en/contacts
      - page: en/calendar
      - page: en/documents
      - page: en/workflow
      - page: en/mail
      - page: en/dashboards
  - page: en/marketing
    icon: fas fa-goal
    children:
      - page: en/campaigns
      - page: en/leads
  - page: en/sales
    icon: fas fa-money
    children:
      - page: en/suppliers
      - page: en/deals
      - page: en/products
      - page: en/orders
  - page: en/projects
    icon: fas fa-money
    children:
      - page: en/tasks
      - page: en/worksheets
      - page: en/projects
      - page: en/issues
  - page: en/supply-chain
    icon: fas fa-home
    children:
      - page: en/warehouses
      - page: en/inventory
  - page: en/finance
    icon: fas fa-home
    children:
      - page: en/invoices
  - page: en/maintenance
    icon: fas fa-home
    children:
      - page: en/notifications
      - page: en/settings
      - page: en/tools
  - page: en/help
    icon: fas fa-home
    children:
      - page: en/about
      - page: en/help


