<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Mon, 19 May 2025 15:20:05 +0200
 */

$conf['title'] = 'Hubleto User Guide';
$conf['template'] = 'mikio';
$conf['plugin']['authldap']['attributes'] = array();
$conf['plugin']['gallery']['options'] = 'cache,crop,lightbox';
