homePage: home
redirects:
  some-old-page:
    newPage: some-new-page
    code: 301
  sk:
    newPage: sk/home
router:
tableOfContents:
  - page: sk/introduction
    icon: fas fa-home
    children:
      - page: sk/introduction/what-is-hubleto
      - page: sk/introduction/who-is-hubleto-for
      - page: sk/introduction/how-to-use-this-guide
  - page: sk/getting-started
    icon: fas fa-play
    children:
      - page: sk/getting-started/registration-and-login
      - page: sk/getting-started/homepage-overview
      - page: sk/getting-started/menu-navigation
  - page: sk/features-overview
    icon: fas fa-star
    children:
      - page: sk/features-overview/ai-assistant
      - page: sk/features-overview/global-search
      - page: sk/features-overview/app-layout-data-grids
      - page: sk/features-overview/record-form-layout
  - page: sk/apps
    icon: fas fa-book
    children:
      - page: sk/apps/crm
        children:
          - page: sk/apps/crm/customers
            icon: fas fa-address-card
          - page: sk/apps/crm/contacts
            icon: fas fa-user
          - page: sk/apps/crm/calendar
            icon: fas fa-calendar-days
          - page: sk/apps/crm/documents
            icon: fa-regular fa-file
          - page: sk/apps/crm/workflow
            icon: fas fa-timeline
          - page: sk/apps/crm/mail
            icon: fas fa-envelope
          - page: sk/apps/crm/tasks
            icon: fas fa-list-check
          - page: sk/apps/crm/dashboards
            icon: fas fa-table
      - page: sk/apps/marketing
        children:
          - page: sk/apps/marketing/campaigns
            icon: fas fa-users-viewfinder
          - page: sk/apps/marketing/leads
            icon: fas fa-people-arrows
      - page: sk/apps/sales
        children:
          - page: sk/apps/sales/suppliers
            icon: fas fa-truck-fast
          - page: sk/apps/sales/deals
            icon: fas fa-handshake
          - page: sk/apps/sales/products
            icon: fas fa-cart-shopping
          - page: sk/apps/sales/orders
            icon: fas fa-money-check-dollar
      - page: sk/apps/productivity
        children:
          - page: sk/apps/productivity/tasks
            icon: fas fa-list-check
          - page: sk/apps/productivity/worksheets
            icon: fas fa-user-clock
          - page: sk/apps/productivity/projects
            icon: fas fa-diagram-project
          - page: sk/apps/productivity/issues
            icon: fas fa-comment
      - page: sk/apps/warehouses
        children:
          - page: sk/apps/warehouses/warehouses
            icon: fas fa-warehouse
          - page: sk/apps/warehouses/inventory
            icon: fas fa-boxes-stacked
      - page: sk/apps/finance
        children:
          - page: sk/apps/finance/invoices
            icon: fas fa-file-invoice
      - page: sk/apps/communication
        children:
          - page: sk/apps/communication/discussions
            icon: fas fa-list-check
      - page: sk/apps/maintenance
        children:
          - page: sk/apps/maintenance/notifications
            icon: fas fa-bell
          - page: sk/apps/maintenance/settings
            icon: fas fa-sliders
          - page: sk/apps/maintenance/tools
            icon: fas fa-screwdriver-wrench
      - page: sk/apps/help
        children:
          - page: sk/apps/help/help
            icon: fas fa-life-ring
          - page: sk/apps/help/about
            icon: fas fa-circle-question
