homePage: home
redirects:
  some-old-page:
    newPage: some-new-page
    code: 301
tableOfContents:
  - page: getting-started
    icon: fas fa-home
    children:
      - page: account-and-setup
      - page: first-steps
      - page: import-customers
      - page: customizing-dashboard
  - page: features
    icon: fas fa-percent
    children:
      - page: customers
      - page: services
      - page: settings
        children:
          - page: settings/users
          - page: settings/profiles
          - page: settings/settings
          - page: settings/tags
          - page: settings/activity-types
          - page: settings/countries
          - page: settings/currencies
          - page: settings/labels
          - page: settings/lead-statuses
          - page: settings/pipelines
      - page: support
        icon: 
  - page: tips-and-tricks
    children:
      - page: customer-data-management
        icon:
        children:
          - page: customer-data-management/customers
          - page: customer-data-management/contact-persons
      - page: sales-pipeline-management
        icon: fas fa-chart-line
        children:
          - page: sales-pipeline-management/sales 
      - page: task-and-activity-tracking
        icon: 
        children:
          - page: task-and-activity-tracking/activities
          - page: task-and-activity-tracking/calendar
