redirects:
  some-old-page:
    newPage: some-new-page
    code: 301
tableOfContents:
  - page: home
    icon: fas fa-home
    children:
      - page: about
        icon: fas fa-question
      - page: getting-started
        icon: fas fa-bolt
        children:
          - page: getting-started/step-1
            icon: fas fa-home
          - page: getting-started/step-2
            icon: fas fa-home
      - page: create-new-account
        icon: fas fa-bla
  - page: contact
pages:
  # sample-page:
  #   pageTemplate: preline-admin/main      # optional, if not provided env.defaultPageConfig.pageTemplate will be used
  home:
    title: Welcome
  about:
    title: About
  getting-started:
    title: Getting started
  create-new-account:
    title: Create new account
  sample-without-sidebar:
  getting-started/step-1:
    title: Step 1
  getting-started/step-2:
    title: Step 2
  contact:
    title: Contact us
