homePage: home
redirects:
  some-old-page:
    newPage: some-new-page
    code: 301
tableOfContents:
  - page: en/getting-started
    icon: fas fa-home
    children:
      - page: en/getting-started/account-and-setup
      - page: en/getting-started/first-steps
  - page: en/modules
    icon: fas fa-folder-open
    children:
      - page: en/modules/contacts
        children:
          - page: en/modules/contacts/add-contact
          - page: en/modules/contacts/edit-contact
          - page: en/modules/contacts/delete-contact
      - page: en/modules/customers
      - page: en/modules/calendar
      - page: en/modules/documents
      - page: en/modules/pipeline
      - page: en/modules/services
      - page: en/modules/leads
        children:
          - page: en/modules/leads/lead-overview
          - page: en/modules/leads/adding-new-leads
          - page: en/modules/leads/updating-lead-info
          - page: en/modules/leads/lead-status-tracking
          - page: en/modules/leads/filtering-and-sorting
          - page: en/modules/leads/lead-conversion
      - page: en/modules/deals
        children:
            - page: en/modules/deals/deal-overview
            - page: en/modules/deals/adding-new-deals
            - page: en/modules/deals/updating-deal-info
            - page: en/modules/deals/deal-status-tracking
            - page: en/modules/deals/filtering-and-sorting
            - page: en/modules/deals/deal-closure
      - page: en/modules/reports
  - page: en/more
    icon: fa-plus 
    children:
      - page: en/more/help
      - page: en/more/upgrade
      - page: en/more/settings
        children:
          - page: en/more/settings/users
          - page: en/more/settings/profiles
          - page: en/more/settings/settings
          - page: en/more/settings/tags
          - page: en/more/settings/activity-types
          - page: en/more/settings/countries
          - page: en/more/settings/currencies
          - page: en/more/settings/labels
          - page: en/more/settings/lead-statuses
          - page: en/more/settings/pipelines
      

