homePage: home
redirects:
  some-old-page:
    newPage: some-new-page
    code: 301
tableOfContents:
  - page: home
    icon: fas fa-home
    children:
      - page: getting-started
        icon: 
        children:
          - page: getting-started/about
          - page: getting-started/account-and-setup
      - page: customer-data-management
        icon:
        children:
          - page: customer-data-management/customers
      - page: sales-pipeline-management
        icon: fas fa-chart-line
        children:
          - page: sales-pipeline-management/sales 
      - page: task-and-activity-tracking
        icon: 
        children:
          - page: task-and-activity-tracking/activities
          - page: task-and-activity-tracking/calendar
