homePage: home
redirects:
  some-old-page:
    newPage: some-new-page
    code: 301
tableOfContents:
  - page: getting-started
    icon: fas fa-home
    children:
      - page: account-and-setup
      - page: first-steps
      - page: import-customers
  - page: features
    icon: fas fa-percent
    children:
      - page: home
        children:
        - page: home/dashboard
        - page: home/adding-new-reports
        - page: home/editing-existing-reports
        - page: home/rearranging-reports
        - page: home/data-fitering
      - page: customers
        children:
        - page: customers/companies
        - page: customers/contact-persons
      - page: calendar
      - page: services
      - page: sales
        children:
          - page: sales/leads
            children: 
            - page: sales/leads/lead-overview
            - page: sales/leads/adding-new-leads
            - page: sales/leads/updating-lead-info
            - page: sales/leads/lead-status-tracking
            - page: sales/leads/filtering-and-sorting
            - page: sales/leads/lead-conversion
          - page: sales/deals
            children: 
            - page: sales/deals/deal-overview
            - page: sales/deals/adding-new-deals
            - page: sales/deals/updating-deal-info
            - page: sales/deals/deal-status-tracking
            - page: sales/deals/filtering-and-sorting
            - page: sales/deals/deal-closure
      - page: settings
        children:
          - page: settings/users
          - page: settings/profiles
          - page: settings/settings
          - page: settings/tags
          - page: settings/activity-types
          - page: settings/countries
          - page: settings/currencies
          - page: settings/labels
          - page: settings/lead-statuses
          - page: settings/pipelines
      - page: support
        icon: 
  - page: tips-and-tricks
    children:
      - page: customer-data-management
        icon:
        children:
          - page: customer-data-management/customers
          - page: customer-data-management/contact-persons
      - page: sales-pipeline-management
        icon: fas fa-chart-line
        children:
          - page: sales-pipeline-management/sales 
      - page: task-and-activity-tracking
        icon: 
        children:
          - page: task-and-activity-tracking/activities
          - page: task-and-activity-tracking/calendar
